module.exports = {
  RandomNumber: require("./randomnumber"),
  Help: require("./help"),
  LuckyNumber: require("./luckynumber"),
  CoolTest: require("./cooltest"),
  SmartTest: require("./smarttest"),
  FlipCoin: require("./flipcoin"),
  Decide: require("./decide"),
  YesorNo: require("./yesorno"),
  Impostor: require("./impostor"),
  Eject: require("./eject"),
  PasswordGen: require("./passwordgen"),
  ColorGen: require("./colorgen"),
  BinaryGen: require("./binarygen"),
  Shuffle: require("./shuffle"),
  Choice: require("./choose"),
  ShuffleSentence: require("./shufflesentence"),
  ShuffleByWord: require("./shufflebyword"),
  Giveaway: require("./giveaway"),
  GiveawaySlash: require("./giveawayslash"),
  Dice: require("./dice"),
  Rate: require("./rate"),
  RiskTest: require("./risktest"),
  Eval: require("./eval"),
}